name: Main Workflow to Deploy to Cloud Run
on:
  workflow_call:

jobs: 
  dev:
    name: develop
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/deploy-run.yml
    with: 
      environment: dev
    secrets: inherit
  stage:
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: ./.github/workflows/deploy-run.yml
    with: 
      environment: stage
    secrets: inherit
  prod: 
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/deploy-run.yml
    with:
      environment: prod
    secrets: inherit